perception_node:
  ros__parameters:
    use_sim_time: True
    tf_frame_camera: head_front_camera_optical_frame
    bt_xml_file: detect_chair.xml
    plugins:
    - is_detected_bt_node
    - identify_bt_node
    - spin_bt_node
    - navigate_to_bt_node
