hri_node:
  ros__parameters:
    use_sim_time: False
    bt_xml_file: query.xml
    prompt_file: prompt.txt
    grammar_file: grammar.txt
    placeholder: "[]"
    plugins:
    - speak_bt_node
    - listen_bt_node
    - query_bt_node

